{
    "name": "CRM Ukrainian Localization",
    "summary": "Ukrainian legal entities, FOP, classifiers, tax data, and employee/contact synchronization",
    "version": "18.0.6.0.0",
    "category": "Localization",
    "license": "LGPL-3",
    "author": "Ivital",
    "depends": [
        "web",
        "contacts",
        "contract",
        "fieldservice",
        "partner_identification",
        "partner_firstname",
        "partner_second_lastname",
        "partner_contact_personal_information_page",
        "partner_contact_birthdate",
        "partner_contact_gender",
        "partner_contact_nationality",
        "partner_contact_birthplace",
        "rating",
        "stock",
        "hr",
        "hr_employee_firstname",
        "hr_employee_second_lastname",
        "hr_employee_id",
        "purchase_stock",
        "portal",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "data/partner_identification_data.xml",
        "data/l10n_ua.kved.csv",
        "data/l10n_ua.kopfg.csv",
        "views/legal_reference_views.xml",
        "views/res_partner_views.xml",
        "views/res_partner_employee_views.xml",
        "views/res_company_views.xml",
        "views/hr_employee_views.xml",
        "views/ukrainian_person_name_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "crm_uk_localization/static/src/js/employee_form_visibility_guard.js",
        ],
    },
    "installable": True,
    "application": False,
}
